# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Pooja Shah
email: me@thepoojashah.com
description: > # this means to ignore newlines until "baseurl:"
  Pooja Shah, theatrical and commercial actress official page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thepoojashah.com" # the base hostname & protocol for your site
twitter_username: ThePoojaShah
github_username:  dtrack

# Build settings
markdown: kramdown

sass:
  style: compressed
